source scripts/environment.sh
source $TOP_DIR/scripts/parts/droidguard.sh
source $TOP_DIR/scripts/parts/fakestore.sh
source $TOP_DIR/scripts/parts/gmscore.sh
source $TOP_DIR/scripts/parts/gsfproxy.sh
source $TOP_DIR/scripts/parts/mapsv1.sh
source $TOP_DIR/scripts/parts/mozillanlpbackend.sh
source $TOP_DIR/scripts/parts/nominatimgeocoderbackend.sh
source $TOP_DIR/scripts/parts/openbmapnlpbackend.sh
